files: ^(?:ToolUniverse/)?src/tooluniverse/
exclude: |
  (?x)(
    ^alignment-handbook/|
    ^deploy/abl/code_logs/|
    ^deploy/old/|
    ^TxAgent/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ] # automatically fix linting issues
      # Run the formatter.
      - id: ruff-format
